### ISSUE TITLE
build error: multiple rules generate `Gem/gem.json`

### ISSUE THREAD

**Issue by ycheng517** [RobotecAI/rai-rosbot-xl-demo#19]
Following the build instructions in the README in the `ros:jazzy` docker cotnainer, I get the following error:

```
root@Predator://rai-rosbot-xl-demo/Project# cmake --build build/linux --config profile --target RAIROSBotXLDemo.Assets RAIROSBotXLDemo.GameLauncher
ninja: error: CMakeFiles/common.ninja:53868: multiple rules generate /rai-rosbot-xl-demo/Project/Gem/gem.json
```

**Comment by jhanca-robotecai** [comment]
I tried to reproduce your error and I created a dockerfile for this. It is still work in progress, but you might be interested to have a look: https://github.com/RobotecAI/rai-rosbot-xl-demo/pull/20

Please let me know if it helps. I will add some guidance about starting O3DE within Docker soon.

**Comment by ycheng517** [comment]
I must've missed a step earlier. #20 works for me! Thanks for implementing the feature
