### ISSUE TITLE
Rosbot is floating

### ISSUE THREAD

**Issue by pijaro** [RobotecAI/rai-rosbot-xl-demo#7]
Rosbot is floating over the floor.

![image](https://github.com/user-attachments/assets/46395ec8-9d40-494d-bb28-83ea72b6d813)

**Comment by jhanca-robotecai** [comment]
The original level was made so the robot does not have to climb the carpets. No idea why. My guess is the other robot was not able to do so. ROSBot does not have such problems. I will change it.
![carpet](https://github.com/user-attachments/assets/7aba7fa0-37e3-4cfd-966e-840c01326ad9)
