### ISSUE TITLE
Consider using hardcoded revision number from stabilization/2409.

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/rai-rosbot-xl-demo#9]
You are using stabilization_branch/2409 for this sim in README :
```
cd $DEMO_BASE
git clone https://github.com/o3de/o3de.git -b stabilization/2409
cd $DEMO_BASE/o3de
git lfs install
git lfs pull
python/get_python.sh
scripts/o3de.sh register --this-engine
```
It is totally fine, but keep in mind that this is a stabilization branch, and a number of folks from O3DE are working on release. If I were you, I would consider to use given, hard, revision number from stabilization/2409, until o3de version 2409 will be released.

**Comment by jhanca-robotecai** [comment]
I see no reason for using the stabilization branch for now, I would stick to the official release. @boczekbartek ?

**Comment by michalpelka** [comment]
Or use release 2310.3 as @jhanca-robotecai proposed!

**Comment by boczekbartek** [comment]
If demo works on release 2310.3 it is fully fine with me to switch.
